apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ochami

resources:
- ../base

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/instance: default-power-control
