---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ochami-postgres
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5
  
  storage:
    size: 5Gi
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: cluster-example-one
spec:
  name: pcsdb
  owner: pcs
  cluster:
    name: ochami-postgres
  schemas:
  - name: pcsdb
    owner: pcs
