---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ochami-postgres
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5
  
  storage:
    size: 5Gi
  managed:
    roles:
    - name: pcs
      ensure: present
      comment: power-control
      login: true
      superuser: false
      passwordSecret:
        name: cluster-ochami-pcs
      inRoles:
        - pg_monitor
        - pg_signal_backend
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: pcsdb
spec:
  name: pcsdb
  owner: pcs
  cluster:
    name: ochami-postgres
  schemas:
  - name: pcsdb
    owner: pcs
---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-ochami-pcs
stringData:
  username: pcs
  password: p0wer!
