---
# Adapted from
# https://raw.githubusercontent.com/percona/percona-postgresql-operator/v2.6.0/deploy/cr.yaml
apiVersion: pgv2.percona.com/v2
kind: PerconaPGCluster
metadata:
  name: power-control-db
spec:
  crVersion: 2.6.0
#  metadata:
#    annotations:
#      example-annotation: value
#    labels:
#      example-label: value


  openshift: false

  autoCreateUserSchema: true

  users:
    - name: pcsuser
      databases:
        - pcsdb
      options: "SUPERUSER"
      password:
        type: ASCII
      secretName: "pcs-db-credentials"

  databaseInitSQL:
    key: pg_single.sql
    name: pcs-init-sql

  image: percona/percona-postgresql-operator:2.6.0-ppg16.8-postgres
  imagePullPolicy: Always
  postgresVersion: 16

  instances:
  - name: power-control
    replicas: 1

    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          podAffinityTerm:
            labelSelector:
              matchLabels:
                postgres-operator.crunchydata.com/data: postgres
            topologyKey: kubernetes.io/hostname
    dataVolumeClaimSpec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi

  proxy:
    pgBouncer:
      replicas: 0

  # Wait, really, they're just stuck on?
  # https://perconadev.atlassian.net/browse/K8SPG-427
  backups:
    pgbackrest:
      image: percona/percona-postgresql-operator:2.6.0-ppg16.8-pgbackrest2.54.2
      repoHost:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
             - weight: 1
               podAffinityTerm:
                 labelSelector:
                   matchLabels:
                     postgres-operator.crunchydata.com/data: pgbackrest
                 topologyKey: kubernetes.io/hostname
      manual:
        repoName: repo1
        options:
         - --type=full
      repos:
      - name: repo1
        schedules:
          full: "0 0 * * 6"
        volume:
          volumeClaimSpec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
  pmm:
    enabled: false
