---
apiVersion: batch/v1
kind: Job
metadata:
  name: ochami-power-control-init
  labels:
    app.kubernetes.io/component: power-service
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/component: power-service
      annotations:
        traffic.sidecar.istio.io/excludeOutboundPorts: 2379,2380
    spec:
      restartPolicy: OnFailure
      # TODO this is a CSM-ism and IDK what to do with it
      #serviceAccountName: "jobs-watcher"
      containers:
      - name: ochami-power-control
        image: power-control-stub
        imagePullPolicy: IfNotPresent
        env:
          - name: LOG_LEVEL
            value: INFO
          - name: STORAGE
            value: POSTGRES
          - name: POSTGRES_HOST
            value: ochami-postgres-rw
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: cluster-ochami-pcs
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: cluster-ochami-pcs
                key: password
          - name: POSTGRES_DBNAME
            value: pcsdb
          - name: POSTGRES_INSECURE
            value: "true"
        command:
          - power-control
          - init-postgres
        securityContext:
          runAsUser: 65534
          runAsGroup: 65534
          runAsNonRoot: true
