apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ochami

resources:
- deployment.yaml
- service.yaml
- istio-virtualservice.yaml

labels:
- includeSelectors: false
  pairs:
    app.kubernetes.io/version: v2.7.0
    app.kubernetes.io/part-of: openchami
