apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ochami

resources:
- deployment.yaml
- service.yaml
- istio-virtualservice.yaml
- init-job.yaml

labels:
- includeSelectors: false
  pairs:
    app.kubernetes.io/version: v2.7.0
    app.kubernetes.io/part-of: openchami
# This exists at the app/ level also; I need to better understand the interactions between multiple
# levels of labels. We need something here to allow independent renders of base/
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: ochami-power-control

images:
- name: power-control-stub
  newName: ghcr.io/rainest/pcs
  newTag: v2.8.3
