apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ochami

resources:
- deployment.yaml
- service.yaml
- istio-virtualservice.yaml

labels:
- includeSelectors: true
  pairs:
    app: power-control
    org: openchami
