---
apiVersion: v1
kind: Service
metadata:
  name: ochami-power-control
  labels:
    app.kubernetes.io/name: ochami-power-control
    app.kubernetes.io/instance: riptide
  annotations:
    cray.io/service: ochami-power-control
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      name: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: ochami-power-control
    app.kubernetes.io/instance: riptide
