---
apiVersion: v1
kind: Service
metadata:
  name: ochami-power-control
  labels:
    app.kubernetes.io/component: power-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      name: http
      protocol: TCP
