name: Run Unit Tests
on:
  - push
  - pull_request
  - workflow_dispatch
jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        storage:
          # This is left as a stub. The tests run by the runUnitTest.sh docker-compose helper do not actually honor
          # the STORAGE variable, though they can see it. https://github.com/OpenCHAMI/power-control/issues/25
          # originally hoped to migrate all tests to a pluggable storage test harness, but this turned out to be much
          # harder than expected.
          - MEMORY
          #- ETCD
          #- POSTGRES
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Install docker compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose make
      - name: Run unit tests
        env:
          STORAGE: ${{ matrix.storage }}
        run: make unittest # this inherits STORAGE from the environment via Makefile directives
