name: Run Integration Tests
on:
  - push
  - pull_request
  - workflow_dispatch
jobs:
  run_integration:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        storage:
          - MEMORY
          - ETCD
          - POSTGRES
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.24.0'
      - name: Run integration tests
        env:
          PCS_TEST_STORAGE: ${{ matrix.storage }}
        run: make integration
